# Site
name: "Super Seniorly"
title: "Super Seniorly"
description: "Tips, tricks, stories, and advice from an intentional 5th year student, AKA super senior."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
#baseurl: /home
google_analytics: 'UA-88769385-2'
disqus: 'superseniorly'
mailchimp-list: 'http://eepurl.com/dC3HjH'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Marianne:
    name: Marianne
    display_name: Marianne
    gravatar: 11148ee2265224cdff65b597027ce3a6
    email: annecruz1996@gmail.com
    web: https://www.superseniorly.com
    twitter: https://twitter.com/mariannecruzat
    description: "An ordinary human leading an extraordinary life."

    #john:
    #name: John
    #display_name: John
    #avatar: 'assets/images/avatar.png'
    #gravatar: b1cc14991db7a456fcd761680bbc8f81
    #email: wowthemesnet@gmail.com
    #web: https://www.wowthemes.net
    #twitter: https://twitter.com/wowthemesnet
    #description: "Testing"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
